<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\StudyProgram;
use App\Models\Curriculum;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $ilmuKomputer = StudyProgram::where('code', 'ILK')->first();

        if (!$ilmuKomputer) {
            $this->command->error('Study Program Ilmu Komputer not found. Please run StudyProgramSeeder first.');
            return;
        }

        // Ambil kurikulum aktif
        $curriculum = Curriculum::where('study_program_id', $ilmuKomputer->id)
            ->where('is_active', true)
            ->first();

        if (!$curriculum) {
            $this->command->error('Active curriculum not found for Ilmu Komputer.');
            return;
        }

        // ======================================
        // MATA KULIAH WAJIB UNIVERSITAS (MKWU)
        // ======================================

        // Semester 1
        $courses = [
            // MKWU Semester 1
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'MEDU.MNCU.001',
                'name' => 'Bahasa Indonesia',
                'english_name' => 'Indonesian Language',
                'type' => 'Wajib Universitas',
                'concentration' => null,
                'credits' => 2,
                'theory_credits' => 2,
                'practice_credits' => 0,
                'field_credits' => 0,
                'semester' => 1,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas tentang penggunaan bahasa Indonesia yang baik dan benar dalam konteks akademik, meliputi penulisan ilmiah, presentasi, dan komunikasi formal.',
                'assessment_methods' => 'Tugas penulisan, ujian tengah semester, ujian akhir semester, presentasi.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'MBU.MNCU.001',
                'name' => 'Pendidikan Pancasila',
                'english_name' => 'Pancasila Education',
                'type' => 'Wajib Universitas',
                'concentration' => null,
                'credits' => 2,
                'theory_credits' => 2,
                'practice_credits' => 0,
                'field_credits' => 0,
                'semester' => 1,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas nilai-nilai Pancasila sebagai dasar negara dan ideologi bangsa, serta penerapannya dalam kehidupan berbangsa dan bernegara.',
                'assessment_methods' => 'Tugas, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],

            // Semester 2
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'MEDU.MNCU.002',
                'name' => 'Pendidikan Kewarganegaraan',
                'english_name' => 'Civic Education',
                'type' => 'Wajib Universitas',
                'concentration' => null,
                'credits' => 2,
                'theory_credits' => 2,
                'practice_credits' => 0,
                'field_credits' => 0,
                'semester' => 2,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas tentang hak dan kewajiban warga negara, konstitusi, demokrasi, HAM, dan wawasan kebangsaan.',
                'assessment_methods' => 'Tugas, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'MBU.MNCU.003',
                'name' => 'Pendidikan Agama',
                'english_name' => 'Religious Education',
                'type' => 'Wajib Universitas',
                'concentration' => null,
                'credits' => 2,
                'theory_credits' => 2,
                'practice_credits' => 0,
                'field_credits' => 0,
                'semester' => 2,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas nilai-nilai agama dan penerapannya dalam kehidupan sehari-hari untuk membentuk karakter yang beretika dan bermoral.',
                'assessment_methods' => 'Tugas, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],

            // Semester 3
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'MEDU.MNCU.003',
                'name' => 'Kewarganegaraan',
                'english_name' => 'Civic Education',
                'type' => 'Wajib Universitas',
                'concentration' => null,
                'credits' => 2,
                'theory_credits' => 2,
                'practice_credits' => 0,
                'field_credits' => 0,
                'semester' => 3,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah lanjutan tentang kewarganegaraan yang membahas isu-isu kontemporer dalam kehidupan berbangsa dan bernegara.',
                'assessment_methods' => 'Tugas, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],

            // Semester 4
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'MEDU.MNCU.004',
                'name' => 'Kepemimpinan',
                'english_name' => 'Leadership',
                'type' => 'Wajib Universitas',
                'concentration' => null,
                'credits' => 2,
                'theory_credits' => 1,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 4,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas teori kepemimpinan, gaya kepemimpinan, dan pengembangan keterampilan kepemimpinan.',
                'assessment_methods' => 'Tugas, presentasi, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'MBU.MNCU.005',
                'name' => 'Literasi Keuangan dan Ekonomi',
                'english_name' => 'Financial and Economic Literacy',
                'type' => 'Wajib Universitas',
                'concentration' => null,
                'credits' => 2,
                'theory_credits' => 2,
                'practice_credits' => 0,
                'field_credits' => 0,
                'semester' => 4,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas konsep dasar literasi keuangan dan ekonomi untuk kehidupan sehari-hari.',
                'assessment_methods' => 'Tugas, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'MBU.MNCU.006',
                'name' => 'Pemikiran Bisnis yang Berorientasi Berkelanjutan',
                'english_name' => 'Sustainable Business Mindset',
                'type' => 'Wajib Universitas',
                'concentration' => null,
                'credits' => 2,
                'theory_credits' => 2,
                'practice_credits' => 0,
                'field_credits' => 0,
                'semester' => 4,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas konsep bisnis berkelanjutan dan tanggung jawab sosial perusahaan.',
                'assessment_methods' => 'Tugas, presentasi, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],

            // ======================================
            // MATA KULIAH PRODI ILMU KOMPUTER (APTIKOM)
            // ======================================

            // Semester 1
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.101',
                'name' => 'Pengantar Teknologi Informasi',
                'english_name' => 'Introduction to Information Technology',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 1,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini memberikan pemahaman dasar tentang teknologi informasi, komputer, sistem operasi, jaringan, dan aplikasi.',
                'assessment_methods' => 'Tugas praktikum, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.102',
                'name' => 'Algoritma dan Pemrograman',
                'english_name' => 'Algorithm and Programming',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 4,
                'theory_credits' => 2,
                'practice_credits' => 2,
                'field_credits' => 0,
                'semester' => 1,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas konsep dasar algoritma, logika pemrograman, dan implementasi dalam bahasa pemrograman.',
                'assessment_methods' => 'Tugas pemrograman, ujian tengah semester, ujian akhir semester, proyek.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.103',
                'name' => 'Matematika Diskrit',
                'english_name' => 'Discrete Mathematics',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 3,
                'practice_credits' => 0,
                'field_credits' => 0,
                'semester' => 1,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas konsep matematika diskrit yang menjadi dasar ilmu komputer.',
                'assessment_methods' => 'Tugas, kuis, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.104',
                'name' => 'Kalkulus',
                'english_name' => 'Calculus',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 3,
                'practice_credits' => 0,
                'field_credits' => 0,
                'semester' => 1,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas konsep kalkulus diferensial dan integral.',
                'assessment_methods' => 'Tugas, kuis, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.105',
                'name' => 'Pengantar Logika dan Himpunan',
                'english_name' => 'Introduction to Logic and Set Theory',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 3,
                'practice_credits' => 0,
                'field_credits' => 0,
                'semester' => 1,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas dasar-dasar logika matematika dan teori himpunan yang menjadi fondasi ilmu komputer.',
                'assessment_methods' => 'Tugas, kuis, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],

            // Semester 2
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.201',
                'name' => 'Struktur Data',
                'english_name' => 'Data Structure',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 4,
                'theory_credits' => 2,
                'practice_credits' => 2,
                'field_credits' => 0,
                'semester' => 2,
                'prerequisites' => 'ILK.102',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas berbagai struktur data dan implementasinya untuk penyelesaian masalah komputasi.',
                'assessment_methods' => 'Tugas pemrograman, ujian tengah semester, ujian akhir semester, proyek.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.202',
                'name' => 'Pemrograman Berorientasi Objek',
                'english_name' => 'Object Oriented Programming',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 4,
                'theory_credits' => 2,
                'practice_credits' => 2,
                'field_credits' => 0,
                'semester' => 2,
                'prerequisites' => 'ILK.102',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas paradigma pemrograman berorientasi objek dan implementasinya.',
                'assessment_methods' => 'Tugas pemrograman, ujian tengah semester, ujian akhir semester, proyek.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.203',
                'name' => 'Basis Data',
                'english_name' => 'Database',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 2,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas konsep sistem basis data, model data, dan SQL.',
                'assessment_methods' => 'Tugas, ujian tengah semester, ujian akhir semester, proyek.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.204',
                'name' => 'Sistem Digital',
                'english_name' => 'Digital System',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 2,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas konsep sistem digital dan logika digital.',
                'assessment_methods' => 'Tugas, laporan praktikum, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.205',
                'name' => 'Aljabar Linear',
                'english_name' => 'Linear Algebra',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 3,
                'practice_credits' => 0,
                'field_credits' => 0,
                'semester' => 2,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas konsep aljabar linear yang menjadi dasar untuk machine learning dan grafika komputer.',
                'assessment_methods' => 'Tugas, kuis, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],

            // Semester 3
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.301',
                'name' => 'Desain dan Analisis Algoritma',
                'english_name' => 'Algorithm Design and Analysis',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 3,
                'practice_credits' => 0,
                'field_credits' => 0,
                'semester' => 3,
                'prerequisites' => 'ILK.201',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas teknik perancangan algoritma dan analisis kompleksitas.',
                'assessment_methods' => 'Tugas, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.302',
                'name' => 'Sistem Operasi',
                'english_name' => 'Operating System',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 3,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas konsep dan prinsip kerja sistem operasi.',
                'assessment_methods' => 'Tugas, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.303',
                'name' => 'Jaringan Komputer',
                'english_name' => 'Computer Network',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 3,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas konsep jaringan komputer, protokol, dan arsitektur jaringan.',
                'assessment_methods' => 'Tugas, ujian tengah semester, ujian akhir semester, proyek.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.304',
                'name' => 'Rekayasa Perangkat Lunak',
                'english_name' => 'Software Engineering',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 3,
                'prerequisites' => 'ILK.202',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas prinsip dan metodologi pengembangan perangkat lunak.',
                'assessment_methods' => 'Tugas, ujian tengah semester, ujian akhir semester, proyek.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.305',
                'name' => 'Probabilitas dan Statistika',
                'english_name' => 'Probability and Statistics',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 3,
                'practice_credits' => 0,
                'field_credits' => 0,
                'semester' => 3,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas konsep probabilitas dan statistika untuk analisis data.',
                'assessment_methods' => 'Tugas, kuis, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],

            // Semester 4
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.401',
                'name' => 'Kecerdasan Buatan',
                'english_name' => 'Artificial Intelligence',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 4,
                'prerequisites' => 'ILK.301',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas konsep kecerdasan buatan, teknik pencarian, dan machine learning dasar.',
                'assessment_methods' => 'Tugas, ujian tengah semester, ujian akhir semester, proyek.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.402',
                'name' => 'Pemrograman Web',
                'english_name' => 'Web Programming',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 4,
                'theory_credits' => 2,
                'practice_credits' => 2,
                'field_credits' => 0,
                'semester' => 4,
                'prerequisites' => 'ILK.203',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas pengembangan aplikasi web menggunakan HTML, CSS, JavaScript, dan framework web.',
                'assessment_methods' => 'Tugas pemrograman, ujian tengah semester, ujian akhir semester, proyek.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.403',
                'name' => 'Interaksi Manusia dan Komputer',
                'english_name' => 'Human Computer Interaction',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 4,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas prinsip desain antarmuka pengguna dan evaluasi usability.',
                'assessment_methods' => 'Tugas desain, ujian tengah semester, ujian akhir semester, proyek.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.404',
                'name' => 'Keamanan Informasi',
                'english_name' => 'Information Security',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 4,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas konsep keamanan informasi, kriptografi, dan security best practices.',
                'assessment_methods' => 'Tugas, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.405',
                'name' => 'Arsitektur dan Organisasi Komputer',
                'english_name' => 'Computer Architecture and Organization',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 3,
                'practice_credits' => 0,
                'field_credits' => 0,
                'semester' => 4,
                'prerequisites' => 'ILK.204',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas arsitektur komputer modern dan organisasi sistem komputer.',
                'assessment_methods' => 'Tugas, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],

            // Semester 5
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.501',
                'name' => 'Machine Learning',
                'english_name' => 'Machine Learning',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 5,
                'prerequisites' => 'ILK.401',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas teknik dan algoritma machine learning untuk analisis dan prediksi data.',
                'assessment_methods' => 'Tugas pemrograman, ujian tengah semester, ujian akhir semester, proyek.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.502',
                'name' => 'Pemrograman Mobile',
                'english_name' => 'Mobile Programming',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 4,
                'theory_credits' => 2,
                'practice_credits' => 2,
                'field_credits' => 0,
                'semester' => 5,
                'prerequisites' => 'ILK.202',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas pengembangan aplikasi mobile untuk platform Android dan iOS.',
                'assessment_methods' => 'Tugas pemrograman, ujian tengah semester, ujian akhir semester, proyek aplikasi.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.503',
                'name' => 'Sistem Basis Data Lanjut',
                'english_name' => 'Advanced Database Systems',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 5,
                'prerequisites' => 'ILK.203',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas konsep database lanjut termasuk NoSQL, data warehousing, dan optimasi query.',
                'assessment_methods' => 'Tugas, ujian tengah semester, ujian akhir semester, proyek.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.504',
                'name' => 'Grafika Komputer',
                'english_name' => 'Computer Graphics',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 5,
                'prerequisites' => 'ILK.205',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas konsep dan teknik grafika komputer 2D dan 3D.',
                'assessment_methods' => 'Tugas pemrograman, ujian tengah semester, ujian akhir semester, proyek.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.505',
                'name' => 'Metodologi Penelitian',
                'english_name' => 'Research Methodology',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 2,
                'theory_credits' => 2,
                'practice_credits' => 0,
                'field_credits' => 0,
                'semester' => 5,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas metodologi penelitian ilmiah dalam bidang ilmu komputer.',
                'assessment_methods' => 'Proposal penelitian, presentasi, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.506',
                'name' => 'Etika Profesi dan Hukum Siber',
                'english_name' => 'Professional Ethics and Cyber Law',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 2,
                'theory_credits' => 2,
                'practice_credits' => 0,
                'field_credits' => 0,
                'semester' => 5,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas etika profesi IT dan aspek hukum terkait teknologi informasi.',
                'assessment_methods' => 'Tugas, presentasi, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],

            // Semester 6
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.601',
                'name' => 'Komputasi Awan',
                'english_name' => 'Cloud Computing',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 6,
                'prerequisites' => 'ILK.303',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas konsep cloud computing, layanan cloud, dan deployment aplikasi di cloud.',
                'assessment_methods' => 'Tugas praktikum, ujian tengah semester, ujian akhir semester, proyek.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.602',
                'name' => 'Pengolahan Citra Digital',
                'english_name' => 'Digital Image Processing',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 6,
                'prerequisites' => 'ILK.305',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas teknik pengolahan citra digital untuk berbagai aplikasi.',
                'assessment_methods' => 'Tugas pemrograman, ujian tengah semester, ujian akhir semester, proyek.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.603',
                'name' => 'Manajemen Proyek Perangkat Lunak',
                'english_name' => 'Software Project Management',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 3,
                'practice_credits' => 0,
                'field_credits' => 0,
                'semester' => 6,
                'prerequisites' => 'ILK.304',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas manajemen proyek dalam pengembangan perangkat lunak.',
                'assessment_methods' => 'Tugas, presentasi, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.604',
                'name' => 'Internet of Things',
                'english_name' => 'Internet of Things',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 6,
                'prerequisites' => 'ILK.303',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas konsep IoT, sensor, aktuator, dan implementasi sistem IoT.',
                'assessment_methods' => 'Tugas, ujian tengah semester, ujian akhir semester, proyek IoT.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.605',
                'name' => 'Technopreneurship',
                'english_name' => 'Technopreneurship',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 2,
                'theory_credits' => 2,
                'practice_credits' => 0,
                'field_credits' => 0,
                'semester' => 6,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas kewirausahaan teknologi dan pengembangan bisnis startup.',
                'assessment_methods' => 'Business plan, pitch presentation, ujian tengah semester, ujian akhir semester.',
                'is_active' => true,
            ],

            // Semester 6 - Kerja Praktik
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.606',
                'name' => 'Kerja Praktik',
                'english_name' => 'Internship',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 2,
                'theory_credits' => 0,
                'practice_credits' => 0,
                'field_credits' => 2,
                'semester' => 6,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mahasiswa melakukan kerja praktik di industri atau institusi untuk mendapatkan pengalaman kerja nyata.',
                'assessment_methods' => 'Laporan kerja praktik, presentasi, evaluasi dari industri.',
                'is_active' => true,
            ],

            // ======================================
            // MATA KULIAH KONSENTRASI - Semester 7
            // ======================================

            // Konsentrasi: Data Science & AI
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.701.DS',
                'name' => 'Deep Learning',
                'english_name' => 'Deep Learning',
                'type' => 'Konsentrasi',
                'concentration' => 'Data Science & AI',
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 7,
                'prerequisites' => 'ILK.501',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas deep learning dan neural networks untuk aplikasi AI kompleks.',
                'assessment_methods' => 'Tugas pemrograman, ujian tengah semester, ujian akhir semester, proyek deep learning.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.702.DS',
                'name' => 'Natural Language Processing',
                'english_name' => 'Natural Language Processing',
                'type' => 'Konsentrasi',
                'concentration' => 'Data Science & AI',
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 7,
                'prerequisites' => 'ILK.501',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas teknik pemrosesan bahasa alami untuk aplikasi AI.',
                'assessment_methods' => 'Tugas pemrograman, ujian tengah semester, ujian akhir semester, proyek NLP.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.703.DS',
                'name' => 'Big Data Analytics',
                'english_name' => 'Big Data Analytics',
                'type' => 'Konsentrasi',
                'concentration' => 'Data Science & AI',
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 7,
                'prerequisites' => 'ILK.503',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas teknik analisis big data menggunakan tools modern.',
                'assessment_methods' => 'Tugas praktikum, ujian tengah semester, ujian akhir semester, proyek big data.',
                'is_active' => true,
            ],

            // Konsentrasi: Software Engineering
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.701.SE',
                'name' => 'Arsitektur Perangkat Lunak',
                'english_name' => 'Software Architecture',
                'type' => 'Konsentrasi',
                'concentration' => 'Software Engineering',
                'credits' => 3,
                'theory_credits' => 3,
                'practice_credits' => 0,
                'field_credits' => 0,
                'semester' => 7,
                'prerequisites' => 'ILK.304',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas pola arsitektur perangkat lunak dan design patterns.',
                'assessment_methods' => 'Tugas desain, ujian tengah semester, ujian akhir semester, proyek arsitektur.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.702.SE',
                'name' => 'Quality Assurance dan Testing',
                'english_name' => 'Quality Assurance and Testing',
                'type' => 'Konsentrasi',
                'concentration' => 'Software Engineering',
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 7,
                'prerequisites' => 'ILK.304',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas teknik quality assurance dan testing perangkat lunak.',
                'assessment_methods' => 'Tugas testing, ujian tengah semester, ujian akhir semester, proyek QA.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.703.SE',
                'name' => 'DevOps dan Continuous Integration',
                'english_name' => 'DevOps and Continuous Integration',
                'type' => 'Konsentrasi',
                'concentration' => 'Software Engineering',
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 7,
                'prerequisites' => 'ILK.601',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas praktik DevOps dan CI/CD untuk delivery perangkat lunak.',
                'assessment_methods' => 'Tugas praktikum, ujian tengah semester, ujian akhir semester, proyek DevOps.',
                'is_active' => true,
            ],

            // Konsentrasi: Network & Security
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.701.NS',
                'name' => 'Keamanan Jaringan Lanjut',
                'english_name' => 'Advanced Network Security',
                'type' => 'Konsentrasi',
                'concentration' => 'Network & Security',
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 7,
                'prerequisites' => 'ILK.404',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas teknik keamanan jaringan tingkat lanjut dan penetration testing.',
                'assessment_methods' => 'Tugas praktikum, ujian tengah semester, ujian akhir semester, proyek security.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.702.NS',
                'name' => 'Forensik Digital',
                'english_name' => 'Digital Forensics',
                'type' => 'Konsentrasi',
                'concentration' => 'Network & Security',
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 7,
                'prerequisites' => 'ILK.404',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas teknik forensik digital untuk investigasi cybercrime.',
                'assessment_methods' => 'Tugas analisis, ujian tengah semester, ujian akhir semester, proyek forensics.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.703.NS',
                'name' => 'Administrasi Server dan Infrastruktur',
                'english_name' => 'Server and Infrastructure Administration',
                'type' => 'Konsentrasi',
                'concentration' => 'Network & Security',
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 7,
                'prerequisites' => 'ILK.302',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas administrasi server Linux/Windows dan manajemen infrastruktur IT.',
                'assessment_methods' => 'Tugas praktikum, ujian tengah semester, ujian akhir semester, proyek administrasi.',
                'is_active' => true,
            ],

            // Semester 7 - Skripsi
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.704',
                'name' => 'Skripsi',
                'english_name' => 'Undergraduate Thesis',
                'type' => 'Wajib Prodi',
                'concentration' => null,
                'credits' => 6,
                'theory_credits' => 0,
                'practice_credits' => 0,
                'field_credits' => 6,
                'semester' => 7,
                'prerequisites' => 'ILK.505',
                'corequisites' => null,
                'description' => 'Mahasiswa melakukan penelitian dan mengembangkan sistem/aplikasi sebagai tugas akhir.',
                'assessment_methods' => 'Skripsi, presentasi, ujian sidang.',
                'is_active' => true,
            ],

            // Semester 7 - Mata Kuliah Pilihan
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.705',
                'name' => 'Blockchain dan Cryptocurrency',
                'english_name' => 'Blockchain and Cryptocurrency',
                'type' => 'Pilihan',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 7,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas teknologi blockchain dan aplikasi cryptocurrency.',
                'assessment_methods' => 'Tugas, ujian tengah semester, ujian akhir semester, proyek blockchain.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.706',
                'name' => 'Game Development',
                'english_name' => 'Game Development',
                'type' => 'Pilihan',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 7,
                'prerequisites' => 'ILK.504',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas pengembangan game menggunakan game engine modern.',
                'assessment_methods' => 'Tugas pemrograman, ujian tengah semester, ujian akhir semester, proyek game.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.707',
                'name' => 'Augmented Reality dan Virtual Reality',
                'english_name' => 'Augmented Reality and Virtual Reality',
                'type' => 'Pilihan',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 7,
                'prerequisites' => 'ILK.504',
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas pengembangan aplikasi AR dan VR.',
                'assessment_methods' => 'Tugas, ujian tengah semester, ujian akhir semester, proyek AR/VR.',
                'is_active' => true,
            ],
            [
                'curriculum_id' => $curriculum->id,
                'study_program_id' => $ilmuKomputer->id,
                'code' => 'ILK.708',
                'name' => 'Sistem Informasi Geografis',
                'english_name' => 'Geographic Information System',
                'type' => 'Pilihan',
                'concentration' => null,
                'credits' => 3,
                'theory_credits' => 2,
                'practice_credits' => 1,
                'field_credits' => 0,
                'semester' => 7,
                'prerequisites' => null,
                'corequisites' => null,
                'description' => 'Mata kuliah ini membahas sistem informasi geografis dan aplikasi pemetaan digital.',
                'assessment_methods' => 'Tugas, ujian tengah semester, ujian akhir semester, proyek GIS.',
                'is_active' => true,
            ],
        ];

        foreach ($courses as $courseData) {
            Course::create($courseData);
        }

        $this->command->info('Courses seeded successfully for Ilmu Komputer!');
    }
}
